package com.graby.store.my;

import com.graby.store.my.ScProcessItem;
import com.graby.store.my.ScProcessItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ScProcessItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_process_item
     *
     * @mbggenerated Thu Jul 23 15:38:22 CST 2015
     */
    int countByExample(ScProcessItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_process_item
     *
     * @mbggenerated Thu Jul 23 15:38:22 CST 2015
     */
    int deleteByExample(ScProcessItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_process_item
     *
     * @mbggenerated Thu Jul 23 15:38:22 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_process_item
     *
     * @mbggenerated Thu Jul 23 15:38:22 CST 2015
     */
    int insert(ScProcessItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_process_item
     *
     * @mbggenerated Thu Jul 23 15:38:22 CST 2015
     */
    int insertSelective(ScProcessItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_process_item
     *
     * @mbggenerated Thu Jul 23 15:38:22 CST 2015
     */
    List<ScProcessItem> selectByExample(ScProcessItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_process_item
     *
     * @mbggenerated Thu Jul 23 15:38:22 CST 2015
     */
    ScProcessItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_process_item
     *
     * @mbggenerated Thu Jul 23 15:38:22 CST 2015
     */
    int updateByExampleSelective(@Param("record") ScProcessItem record, @Param("example") ScProcessItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_process_item
     *
     * @mbggenerated Thu Jul 23 15:38:22 CST 2015
     */
    int updateByExample(@Param("record") ScProcessItem record, @Param("example") ScProcessItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_process_item
     *
     * @mbggenerated Thu Jul 23 15:38:22 CST 2015
     */
    int updateByPrimaryKeySelective(ScProcessItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_process_item
     *
     * @mbggenerated Thu Jul 23 15:38:22 CST 2015
     */
    int updateByPrimaryKey(ScProcessItem record);
}