package com.graby.store.entity;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
@Entity
@Table(name = "sc_process_item")
public class ProcessItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_process_item.id
     *
     * @mbggenerated Thu Jul 23 15:38:22 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_process_item.type
     *
     * @mbggenerated Thu Jul 23 15:38:22 CST 2015
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_process_item.itemCode
     *
     * @mbggenerated Thu Jul 23 15:38:22 CST 2015
     */
    private String itemcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_process_item.itemId
     *
     * @mbggenerated Thu Jul 23 15:38:22 CST 2015
     */
    private String itemid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_process_item.inventoryType
     *
     * @mbggenerated Thu Jul 23 15:38:22 CST 2015
     */
    private String inventorytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_process_item.quantity
     *
     * @mbggenerated Thu Jul 23 15:38:22 CST 2015
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_process_item.productDate
     *
     * @mbggenerated Thu Jul 23 15:38:22 CST 2015
     */
    private Date productdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_process_item.expireDate
     *
     * @mbggenerated Thu Jul 23 15:38:22 CST 2015
     */
    private Date expiredate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_process_item.produceCode
     *
     * @mbggenerated Thu Jul 23 15:38:22 CST 2015
     */
    private String producecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_process_item.remark
     *
     * @mbggenerated Thu Jul 23 15:38:22 CST 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_process_item.parentId
     *
     * @mbggenerated Thu Jul 23 15:38:22 CST 2015
     */
    private Integer parentid;

   @Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_process_item.id
     *
     * @param id the value for sc_process_item.id
     *
     * @mbggenerated Thu Jul 23 15:38:22 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_process_item.type
     *
     * @return the value of sc_process_item.type
     *
     * @mbggenerated Thu Jul 23 15:38:22 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_process_item.type
     *
     * @param type the value for sc_process_item.type
     *
     * @mbggenerated Thu Jul 23 15:38:22 CST 2015
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_process_item.itemCode
     *
     * @return the value of sc_process_item.itemCode
     *
     * @mbggenerated Thu Jul 23 15:38:22 CST 2015
     */
    public String getItemcode() {
        return itemcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_process_item.itemCode
     *
     * @param itemcode the value for sc_process_item.itemCode
     *
     * @mbggenerated Thu Jul 23 15:38:22 CST 2015
     */
    public void setItemcode(String itemcode) {
        this.itemcode = itemcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_process_item.itemId
     *
     * @return the value of sc_process_item.itemId
     *
     * @mbggenerated Thu Jul 23 15:38:22 CST 2015
     */
    public String getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_process_item.itemId
     *
     * @param itemid the value for sc_process_item.itemId
     *
     * @mbggenerated Thu Jul 23 15:38:22 CST 2015
     */
    public void setItemid(String itemid) {
        this.itemid = itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_process_item.inventoryType
     *
     * @return the value of sc_process_item.inventoryType
     *
     * @mbggenerated Thu Jul 23 15:38:22 CST 2015
     */
    public String getInventorytype() {
        return inventorytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_process_item.inventoryType
     *
     * @param inventorytype the value for sc_process_item.inventoryType
     *
     * @mbggenerated Thu Jul 23 15:38:22 CST 2015
     */
    public void setInventorytype(String inventorytype) {
        this.inventorytype = inventorytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_process_item.quantity
     *
     * @return the value of sc_process_item.quantity
     *
     * @mbggenerated Thu Jul 23 15:38:22 CST 2015
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_process_item.quantity
     *
     * @param quantity the value for sc_process_item.quantity
     *
     * @mbggenerated Thu Jul 23 15:38:22 CST 2015
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_process_item.productDate
     *
     * @return the value of sc_process_item.productDate
     *
     * @mbggenerated Thu Jul 23 15:38:22 CST 2015
     */
    public Date getProductdate() {
        return productdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_process_item.productDate
     *
     * @param productdate the value for sc_process_item.productDate
     *
     * @mbggenerated Thu Jul 23 15:38:22 CST 2015
     */
    public void setProductdate(Date productdate) {
        this.productdate = productdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_process_item.expireDate
     *
     * @return the value of sc_process_item.expireDate
     *
     * @mbggenerated Thu Jul 23 15:38:22 CST 2015
     */
    public Date getExpiredate() {
        return expiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_process_item.expireDate
     *
     * @param expiredate the value for sc_process_item.expireDate
     *
     * @mbggenerated Thu Jul 23 15:38:22 CST 2015
     */
    public void setExpiredate(Date expiredate) {
        this.expiredate = expiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_process_item.produceCode
     *
     * @return the value of sc_process_item.produceCode
     *
     * @mbggenerated Thu Jul 23 15:38:22 CST 2015
     */
    public String getProducecode() {
        return producecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_process_item.produceCode
     *
     * @param producecode the value for sc_process_item.produceCode
     *
     * @mbggenerated Thu Jul 23 15:38:22 CST 2015
     */
    public void setProducecode(String producecode) {
        this.producecode = producecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_process_item.remark
     *
     * @return the value of sc_process_item.remark
     *
     * @mbggenerated Thu Jul 23 15:38:22 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_process_item.remark
     *
     * @param remark the value for sc_process_item.remark
     *
     * @mbggenerated Thu Jul 23 15:38:22 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_process_item.parentId
     *
     * @return the value of sc_process_item.parentId
     *
     * @mbggenerated Thu Jul 23 15:38:22 CST 2015
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_process_item.parentId
     *
     * @param parentid the value for sc_process_item.parentId
     *
     * @mbggenerated Thu Jul 23 15:38:22 CST 2015
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }
}